### ISSUE TITLE
Scraper doesnt handle ID variations

### ISSUE THREAD

**Issue by Brinsby** [TrevorBagels/PulsepointScraperV2#2]
I tried to use this to monitor my local fd and ems. When I put in the agencies around me I get the following error.

Desktop\PulsepointScraperV2-main\PulsepointScraperV2-main\dev\prodict\__init__.py", line 234, in set_attribute
    self.update({attr_name: constructor(value)})
ValueError: invalid literal for int() with base 10: 'EMS1252'

It looks like the program is expecting a pure int but I guess fire stations and ems around me stipulate that they are EMS in their ID through pulsepoint? 

Either way I tracked this back to line 174 in main.py it looks like when you set the ID=a_id this needs to have any alphanumeric characters stripped from it to work

Here is my config if you want to try it
{
    "api_key": "",
    "pushover_token": "",
    "pushover_user": "",
    "scan_interval": "1m",
    "radius_default": "12.2mi",
"agencies": [
        {    
            "name": "Allegheny County Emergency Services"
        }
    ],
    "locations": [
        {   "name": "Allegheny County",
            "address": "525 William Penn Pl, Pittsburgh, PA 15219",
            "coords": [40.441405090547704, -80.003636928768],
            "filters": {
                "allowed": ["Fire Alarm"],
                "blocked": []
            }
        }
    ]
}

**Comment by TrevorBagels** [comment]
Looking into it now, I'll let you know when it's resolved.

**Comment by TrevorBagels** [comment]
Fixed it! Feel free to pull the changes, everything should work now.
